
use LIBRARY;

SELECT BOOK_COPIES.No_of_copies FROM BOOK , BOOK_COPIES , LIBRARY_BRANCH WHERE BOOK.Book_id = BOOK_COPIES.Book_id AND BOOK_COPIES.Branch_id = LIBRARY_BRANCH.Branch_id AND Title='The Lost Tribe' AND Branch_name='Sharpstown';

SELECT LIBRARY_BRANCH.Branch_name, BOOK_COPIES.No_of_copies FROM BOOK , BOOK_COPIES , LIBRARY_BRANCH WHERE BOOK.Book_id = BOOK_COPIES.Book_id AND LIBRARY_BRANCH.Branch_id = BOOK_COPIES.Branch_id AND Title='The Lost Tribe';

SELECT Borrower_name FROM BORROWER WHERE NOT EXISTS (SELECT * FROM BOOK_LOANS WHERE BORROWER.Card_no = BOOK_LOANS.Card_no );

SELECT BOOK.Title, BORROWER.Borrower_name, BORROWER.Address FROM BOOK , BORROWER , BOOK_LOANS , LIBRARY_BRANCH WHERE LIBRARY_BRANCH.Branch_name='Sharpstown' AND LIBRARY_BRANCH.Branch_id = BOOK_LOANS.Branch_id AND BOOK_LOANS.Due_date = current_date() AND BOOK_LOANS.Card_no = BORROWER.Card_no AND BOOK_LOANS.Book_id = BOOK.Book_id;

SELECT LIBRARY_BRANCH.Branch_name, COUNT(*) FROM LIBRARY_BRANCH , BOOK_LOANS WHERE BOOK_LOANS.Branch_id = LIBRARY_BRANCH.Branch_id GROUP BY LIBRARY_BRANCH.Branch_name;

SELECT BORROWER.Borrower_name, BORROWER.Address, COUNT(*) FROM BORROWER , BOOK_LOANS WHERE BORROWER.Card_no = BOOK_LOANS.Card_no GROUP BY BORROWER.Card_no, BORROWER.Borrower_name, BORROWER.Address HAVING COUNT(*) > 5;

SELECT BOOK.Title, BOOK_COPIES.No_of_copies FROM BOOK_AUTHORS , BOOK , BOOK_COPIES , LIBRARY_BRANCH WHERE BOOK.Book_id = BOOK_AUTHORS.Book_id AND BOOK.Book_id = BOOK_COPIES.Book_id AND LIBRARY_BRANCH.Branch_id = BOOK_COPIES.Branch_id AND Author_name='Stephen King' AND Branch_name='Central';

